FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]

# docker build -t next-first-steps .
# docker run -p 3000:3000 next-first-steps
